import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";
import Header from "@/app/components/Header";
import { NextAuthProvider } from "@/app/lib/next-auth/provider";
import { Suspense } from "react";
import LoadingSpinner from "@/app/loading";

// 変数定義とエクスポート
const notoSansJP = Noto_Sans_JP({
    subsets: ["latin"],
    variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
    title: "Book Commerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // jaに変更
        <html lang="ja">
            {/* フォント名.classNameで反映 */}
            <body className={notoSansJP.className}>
                <NextAuthProvider>
                    <Header />
                    <Suspense fallback={<LoadingSpinner/>}>{children}</Suspense>
                </NextAuthProvider>
            </body>
        </html>
    );
}
